export const mock = {
  id: 2,
  user_id: 12,
  name: "One Cent Stamp",
  uuid: "I-Fij1853-8956344",
  status: ["FOR_TRADE", "FOR_REFERENCE", "FOR_EXHIBITION"],
  country: "Fiji",
  year_issued: "1853",
  denomination: "23",
  perforation: null,
  color: null,
  condition: "Used",
  grade: null,
  format: "Plate Block",
  total_stamps_issued: null,
  coins_value: 1200,
  related_set_stamps_count: null,
  quality: ["Lightly Hinged (LH)", "Hinged Remaining (HR)"],
  shape: null,
  quantity_owned: {
    used: null,
    mint: null,
  },
  issue_type: null,
  created_by: 12,
  updated_by: 12,
  description: "Stamp Description",
  created_at: "2023-03-06T11:38:55.000000Z",
  updated_at: "2023-03-06T17:20:29.000000Z",
  deleted_at: null,
  flag_tickets_count: 2,
  is_flagged_by_current_user: 0,
  is_wishable: 0,
  is_attached_in_auctions: 0,
  is_attached_in_trades: 1,
  is_attached_in_supply: 0,
  is_item_placed_in_trade_offer: 0,
  catalogue_number: [
    {
      id: 10,
      stamp_item_id: 2,
      type: "Michael’s",
      number: "12345",
      year: 2020,
      value: "12.00",
    },
  ],
  user: {
    id: 12,
    first_name: "Lois",
    last_name: "Charter",
    username: "lois",
    image: "users/user-12/profile-images/16781990545085.",
    cover_image: null,
    email: "giyahon214@vootin.com",
    phone: "+12708175769",
    description: null,
    language: "English (United States)",
    gender: "Male",
    dob: 1980,
    is_email_verified: 1,
    uid: "aO8cd7R7aGR1sW021Z2sNV0sjx52",
    coins: 77,
    wallet_balance: 0,
    mrs_badge: "Beginner",
    caco_level: "Enthusiast",
    type: "member",
    status: "Active",
    created_at: "2023-03-06T10:28:35.000000Z",
    updated_at: "2023-04-06T10:40:02.000000Z",
    stripe_id: "cus_NTYOe6rPX1bVpj",
    pm_type: "visa",
    pm_last_four: "4242",
    trial_ends_at: null,
    deleted_at: null,
    full_name: "Lois Charter",
    image_url:
      "https://stampbox-project-dev.s3.us-east-2.amazonaws.com/users/user-12/profile-images/16781990545085.",
    cover_image_url:
      "https://devapi.stampbox.com/default-images/banner_thumbnail.png",
    rating: 0,
    is_payment_method_attached: true,
    profile_viewable_name: "Lois Charter",
    ratings: [
      {
        id: 12,
        user_id: 12,
        type: "TFS",
        rating: "0.00",
        created_at: "2023-03-06T10:28:35.000000Z",
        updated_at: "2023-03-06T10:28:35.000000Z",
        deleted_at: null,
      },
    ],
  },
  categories: [],
  albums: [],
  medias: [
    {
      id: 5,
      user_id: 12,
      is_stamp: 1,
      media: "users/user-12/item-media/16781025256539.jpeg",
      linked_with: "stamp",
      type: "actual",
      created_at: "2023-03-06T11:35:25.000000Z",
      updated_at: "2023-03-06T11:35:25.000000Z",
      deleted_at: null,
      media_url:
        "https://d30hji56ulrnvw.cloudfront.net/users/user-12/item-media/16781025256539.jpeg",
      pivot: {
        mediable_id: 2,
        media_id: 5,
        mediable_type: "StampItem",
      },
    },
  ],
  trade_offers: [],
};
// export const mockres = {
//   success: true,
//   message: "Similar Items fetched successfully",
//   result: [
//     {
//       id: 2,
//       user_id: 12,
//       name: "One Cent Stamp",
//       uuid: "I-Fij1853-8956344",
//       status: ["FOR_TRADE", "FOR_REFERENCE", "FOR_EXHIBITION"],
//       country: "Fiji",
//       year_issued: "1853",
//       denomination: "23",
//       perforation: null,
//       color: null,
//       condition: "Used",
//       grade: null,
//       format: "Plate Block",
//       total_stamps_issued: null,
//       coins_value: 1200,
//       related_set_stamps_count: null,
//       quality: ["Lightly Hinged (LH)", "Hinged Remaining (HR)"],
//       shape: null,
//       quantity_owned: {
//         used: null,
//         mint: null,
//       },
//       issue_type: null,
//       created_by: 12,
//       updated_by: 12,
//       description: "Stamp Description",
//       created_at: "2023-03-06T11:38:55.000000Z",
//       updated_at: "2023-03-06T17:20:29.000000Z",
//       deleted_at: null,
//       flag_tickets_count: 2,
//       is_flagged_by_current_user: 0,
//       is_wishable: 0,
//       is_attached_in_auctions: 0,
//       is_attached_in_trades: 1,
//       is_attached_in_supply: 0,
//       is_item_placed_in_trade_offer: 0,
//       catalogue_number: [
//         {
//           id: 10,
//           stamp_item_id: 2,
//           type: "Michael’s",
//           number: "12345",
//           year: 2020,
//           value: "12.00",
//         },
//       ],
//       user: {
//         id: 12,
//         first_name: "Lois",
//         last_name: "Charter",
//         username: "lois",
//         image: "users/user-12/profile-images/16781990545085.",
//         cover_image: null,
//         email: "giyahon214@vootin.com",
//         phone: "+12708175769",
//         description: null,
//         language: "English (United States)",
//         gender: "Male",
//         dob: 1980,
//         is_email_verified: 1,
//         uid: "aO8cd7R7aGR1sW021Z2sNV0sjx52",
//         coins: 77,
//         wallet_balance: 0,
//         mrs_badge: "Beginner",
//         caco_level: "Enthusiast",
//         type: "member",
//         status: "Active",
//         created_at: "2023-03-06T10:28:35.000000Z",
//         updated_at: "2023-04-06T10:40:02.000000Z",
//         stripe_id: "cus_NTYOe6rPX1bVpj",
//         pm_type: "visa",
//         pm_last_four: "4242",
//         trial_ends_at: null,
//         deleted_at: null,
//         full_name: "Lois Charter",
//         image_url:
//           "https://stampbox-project-dev.s3.us-east-2.amazonaws.com/users/user-12/profile-images/16781990545085.",
//         cover_image_url:
//           "https://devapi.stampbox.com/default-images/banner_thumbnail.png",
//         rating: 0,
//         is_payment_method_attached: true,
//         profile_viewable_name: "Lois Charter",
//         ratings: [
//           {
//             id: 12,
//             user_id: 12,
//             type: "TFS",
//             rating: "0.00",
//             created_at: "2023-03-06T10:28:35.000000Z",
//             updated_at: "2023-03-06T10:28:35.000000Z",
//             deleted_at: null,
//           },
//         ],
//       },
//       categories: [],
//       albums: [],
//       medias: [
//         {
//           id: 5,
//           user_id: 12,
//           is_stamp: 1,
//           media: "users/user-12/item-media/16781025256539.jpeg",
//           linked_with: "stamp",
//           type: "actual",
//           created_at: "2023-03-06T11:35:25.000000Z",
//           updated_at: "2023-03-06T11:35:25.000000Z",
//           deleted_at: null,
//           media_url:
//             "https://d30hji56ulrnvw.cloudfront.net/users/user-12/item-media/16781025256539.jpeg",
//           pivot: {
//             mediable_id: 2,
//             media_id: 5,
//             mediable_type: "StampItem",
//           },
//         },
//       ],
//       trade_offers: [],
//     },
//     {
//       id: 16,
//       user_id: 13,
//       name: "ICELAND5GOLD",
//       uuid: "I-Den1912-3358713",
//       status: ["FOR_AUCTION"],
//       country: "Denmark",
//       year_issued: "1912",
//       denomination: null,
//       perforation: null,
//       color: null,
//       condition: null,
//       grade: null,
//       format: "Incomplete Set",
//       total_stamps_issued: null,
//       coins_value: 3300,
//       related_set_stamps_count: null,
//       quality: [],
//       shape: null,
//       quantity_owned: {
//         used: null,
//         mint: null,
//       },
//       issue_type: null,
//       created_by: 13,
//       updated_by: 13,
//       description: null,
//       created_at: "2023-03-13T11:25:18.000000Z",
//       updated_at: "2023-03-14T16:34:47.000000Z",
//       deleted_at: null,
//       flag_tickets_count: 0,
//       is_flagged_by_current_user: 0,
//       is_wishable: 0,
//       is_attached_in_auctions: 0,
//       is_attached_in_trades: 0,
//       is_attached_in_supply: 0,
//       is_item_placed_in_trade_offer: 0,
//       catalogue_number: [
//         {
//           id: 34,
//           stamp_item_id: 16,
//           type: "Scott",
//           number: "222",
//           year: 2022,
//           value: "33.00",
//         },
//       ],
//       user: {
//         id: 13,
//         first_name: "Shafqat Shah",
//         last_name: null,
//         username: "shafqat1678100610901",
//         image: null,
//         cover_image: null,
//         email: "shafqat@pixarsart.com",
//         phone: "+1 234 555 5555",
//         description:
//           "Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum ",
//         language: null,
//         gender: null,
//         dob: null,
//         is_email_verified: 1,
//         uid: "Z8y4RnCbN9RVEay6kAdpeFUobDu1",
//         coins: 2998,
//         wallet_balance: 57,
//         mrs_badge: "Beginner",
//         caco_level: "Enthusiast",
//         type: "member",
//         status: "Active",
//         created_at: "2023-03-06T11:03:32.000000Z",
//         updated_at: "2023-04-07T17:19:20.000000Z",
//         stripe_id: "cus_NTYxC370vol8BD",
//         pm_type: "visa",
//         pm_last_four: "4242",
//         trial_ends_at: null,
//         deleted_at: null,
//         full_name: "Shafqat Shah ",
//         image_url: "https://devapi.stampbox.com/default_user_image.png",
//         cover_image_url:
//           "https://devapi.stampbox.com/default-images/banner_thumbnail.png",
//         rating: 3.35,
//         is_payment_method_attached: true,
//         profile_viewable_name: "Shafqat Shah ",
//         ratings: [
//           {
//             id: 13,
//             user_id: 13,
//             type: "TFS",
//             rating: "3.35",
//             created_at: "2023-03-06T11:03:32.000000Z",
//             updated_at: "2023-04-07T18:51:39.000000Z",
//             deleted_at: null,
//           },
//         ],
//       },
//       categories: [
//         {
//           id: 16,
//           name: "Errors",
//           image: "errors.png",
//           type: "stamp_items",
//           parent_id: null,
//           created_at: "2023-03-06T09:54:50.000000Z",
//           updated_at: "2023-03-06T09:54:50.000000Z",
//           deleted_at: null,
//           image_url:
//             "https://devapi.stampbox.com/storage/category-images/errors.png",
//           pivot: {
//             categorizable_id: 16,
//             category_id: 16,
//             categorizable_type: "StampItem",
//           },
//         },
//       ],
//       albums: [
//         {
//           id: 14,
//           user_id: 13,
//           name: "Lot 3",
//           image: "users/user-13/album-covers/16789911705214.png",
//           description:
//             "Descript of lot, is lot very painfull, Doctor its paining here",
//           type: "Lot",
//           is_private: 1,
//           created_at: "2023-03-16T18:26:10.000000Z",
//           updated_at: "2023-03-31T14:48:21.000000Z",
//           deleted_at: null,
//           image_url:
//             "https://stampbox-project-dev.s3.us-east-2.amazonaws.com/users/user-13/album-covers/16789911705214.png",
//           pivot: {
//             stamp_item_id: 16,
//             album_id: 14,
//           },
//         },
//         {
//           id: 30,
//           user_id: 13,
//           name: "Lot of stmaps",
//           image: "users/user-13/album-covers/16795755546902.png",
//           description: null,
//           type: "Lot",
//           is_private: 1,
//           created_at: "2023-03-23T12:45:54.000000Z",
//           updated_at: "2023-03-31T14:47:27.000000Z",
//           deleted_at: null,
//           image_url:
//             "https://stampbox-project-dev.s3.us-east-2.amazonaws.com/users/user-13/album-covers/16795755546902.png",
//           pivot: {
//             stamp_item_id: 16,
//             album_id: 30,
//           },
//         },
//         {
//           id: 35,
//           user_id: 13,
//           name: "New albums",
//           image: null,
//           description: null,
//           type: "Album",
//           is_private: 0,
//           created_at: "2023-03-23T19:07:56.000000Z",
//           updated_at: "2023-03-23T19:07:56.000000Z",
//           deleted_at: null,
//           image_url:
//             "https://devapi.stampbox.com/default-images/albums-thumbnail.png",
//           pivot: {
//             stamp_item_id: 16,
//             album_id: 35,
//           },
//         },
//       ],
//       medias: [
//         {
//           id: 16,
//           user_id: 13,
//           is_stamp: 1,
//           media: "users/user-13/item-media/16781145432856.png",
//           linked_with: "stamp",
//           type: "actual",
//           created_at: "2023-03-06T14:55:43.000000Z",
//           updated_at: "2023-03-23T14:11:50.000000Z",
//           deleted_at: null,
//           media_url:
//             "https://d30hji56ulrnvw.cloudfront.net/users/user-13/item-media/16781145432856.png",
//           pivot: {
//             mediable_id: 16,
//             media_id: 16,
//             mediable_type: "StampItem",
//           },
//         },
//       ],
//       trade_offers: [],
//     },
//     {
//       id: 20,
//       user_id: 19,
//       name: "USA$2.40Demo 2",
//       uuid: "I-Uni1968-8666235",
//       status: ["FOR_TRADE", "FOR_AUCTION"],
//       country: "United States",
//       year_issued: "1968",
//       denomination: null,
//       perforation: null,
//       color: null,
//       condition: null,
//       grade: null,
//       format: "Incomplete Set",
//       total_stamps_issued: null,
//       coins_value: 2,
//       related_set_stamps_count: null,
//       quality: [],
//       shape: null,
//       quantity_owned: {
//         used: null,
//         mint: null,
//       },
//       issue_type: null,
//       created_by: 19,
//       updated_by: 19,
//       description: null,
//       created_at: "2023-03-22T12:21:20.000000Z",
//       updated_at: "2023-03-22T12:21:20.000000Z",
//       deleted_at: null,
//       flag_tickets_count: 2,
//       is_flagged_by_current_user: 0,
//       is_wishable: 0,
//       is_attached_in_auctions: 1,
//       is_attached_in_trades: 0,
//       is_attached_in_supply: 0,
//       is_item_placed_in_trade_offer: 0,
//       catalogue_number: [
//         {
//           id: 40,
//           stamp_item_id: 20,
//           type: null,
//           number: null,
//           year: null,
//           value: null,
//         },
//       ],
//       user: {
//         id: 19,
//         first_name: "Mr. Palermo",
//         last_name: null,
//         username: "i.am.palermo81678128033751",
//         image: null,
//         cover_image: null,
//         email: "i.am.palermo8@gmail.com",
//         phone: "+1 234 555 5522",
//         description: null,
//         language: null,
//         gender: null,
//         dob: null,
//         is_email_verified: 1,
//         uid: "AkWMW9zouEQuPCHj0l6eCOlOHQh1",
//         coins: 90,
//         wallet_balance: 0,
//         mrs_badge: "Beginner",
//         caco_level: "Enthusiast",
//         type: "member",
//         status: "Active",
//         created_at: "2023-03-06T18:40:35.000000Z",
//         updated_at: "2023-04-06T18:50:03.000000Z",
//         stripe_id: "cus_NTgKwBwZdq8ga7",
//         pm_type: "visa",
//         pm_last_four: "4242",
//         trial_ends_at: null,
//         deleted_at: null,
//         full_name: "Mr. Palermo ",
//         image_url: "https://devapi.stampbox.com/default_user_image.png",
//         cover_image_url:
//           "https://devapi.stampbox.com/default-images/banner_thumbnail.png",
//         rating: 0,
//         is_payment_method_attached: true,
//         profile_viewable_name: "Mr. Palermo ",
//         ratings: [
//           {
//             id: 19,
//             user_id: 19,
//             type: "TFS",
//             rating: "0.00",
//             created_at: "2023-03-06T18:40:35.000000Z",
//             updated_at: "2023-03-06T18:40:35.000000Z",
//             deleted_at: null,
//           },
//         ],
//       },
//       categories: [
//         {
//           id: 16,
//           name: "Errors",
//           image: "errors.png",
//           type: "stamp_items",
//           parent_id: null,
//           created_at: "2023-03-06T09:54:50.000000Z",
//           updated_at: "2023-03-06T09:54:50.000000Z",
//           deleted_at: null,
//           image_url:
//             "https://devapi.stampbox.com/storage/category-images/errors.png",
//           pivot: {
//             categorizable_id: 20,
//             category_id: 16,
//             categorizable_type: "StampItem",
//           },
//         },
//       ],
//       albums: [
//         {
//           id: 20,
//           user_id: 19,
//           name: "Palermo's Lot",
//           image: null,
//           description:
//             "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
//           type: "Lot",
//           is_private: 0,
//           created_at: "2023-03-22T11:56:40.000000Z",
//           updated_at: "2023-03-22T11:56:40.000000Z",
//           deleted_at: null,
//           image_url:
//             "https://devapi.stampbox.com/default-images/albums-thumbnail.png",
//           pivot: {
//             stamp_item_id: 20,
//             album_id: 20,
//           },
//         },
//       ],
//       medias: [
//         {
//           id: 94,
//           user_id: 19,
//           is_stamp: 1,
//           media: "users/user-19/item-media/16794876029542.",
//           linked_with: "stamp",
//           type: "actual",
//           created_at: "2023-03-22T12:20:03.000000Z",
//           updated_at: "2023-03-22T12:20:03.000000Z",
//           deleted_at: null,
//           media_url:
//             "https://d30hji56ulrnvw.cloudfront.net/users/user-19/item-media/16794876029542.",
//           pivot: {
//             mediable_id: 20,
//             media_id: 94,
//             mediable_type: "StampItem",
//           },
//         },
//       ],
//       trade_offers: [],
//     },
//     {
//       id: 33,
//       user_id: 13,
//       name: "STATESPOSTAGETEDONE CENT",
//       uuid: "I-Uni1902-4566915",
//       status: ["FOR_SALE"],
//       country: "United States",
//       year_issued: "1902",
//       denomination: null,
//       perforation: null,
//       color: null,
//       condition: null,
//       grade: null,
//       format: "Incomplete Set",
//       total_stamps_issued: null,
//       coins_value: 22001,
//       related_set_stamps_count: null,
//       quality: [],
//       shape: null,
//       quantity_owned: {
//         used: null,
//         mint: null,
//       },
//       issue_type: "N/A",
//       created_by: 13,
//       updated_by: 13,
//       description: null,
//       created_at: "2023-03-27T17:40:53.000000Z",
//       updated_at: "2023-03-27T17:40:53.000000Z",
//       deleted_at: null,
//       flag_tickets_count: 0,
//       is_flagged_by_current_user: 0,
//       is_wishable: 0,
//       is_attached_in_auctions: 0,
//       is_attached_in_trades: 0,
//       is_attached_in_supply: 0,
//       is_item_placed_in_trade_offer: 0,
//       catalogue_number: [
//         {
//           id: 57,
//           stamp_item_id: 33,
//           type: "Scott",
//           number: null,
//           year: null,
//           value: "22.00",
//         },
//       ],
//       user: {
//         id: 13,
//         first_name: "Shafqat Shah",
//         last_name: null,
//         username: "shafqat1678100610901",
//         image: null,
//         cover_image: null,
//         email: "shafqat@pixarsart.com",
//         phone: "+1 234 555 5555",
//         description:
//           "Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum ",
//         language: null,
//         gender: null,
//         dob: null,
//         is_email_verified: 1,
//         uid: "Z8y4RnCbN9RVEay6kAdpeFUobDu1",
//         coins: 2998,
//         wallet_balance: 57,
//         mrs_badge: "Beginner",
//         caco_level: "Enthusiast",
//         type: "member",
//         status: "Active",
//         created_at: "2023-03-06T11:03:32.000000Z",
//         updated_at: "2023-04-07T17:19:20.000000Z",
//         stripe_id: "cus_NTYxC370vol8BD",
//         pm_type: "visa",
//         pm_last_four: "4242",
//         trial_ends_at: null,
//         deleted_at: null,
//         full_name: "Shafqat Shah ",
//         image_url: "https://devapi.stampbox.com/default_user_image.png",
//         cover_image_url:
//           "https://devapi.stampbox.com/default-images/banner_thumbnail.png",
//         rating: 3.35,
//         is_payment_method_attached: true,
//         profile_viewable_name: "Shafqat Shah ",
//         ratings: [
//           {
//             id: 13,
//             user_id: 13,
//             type: "TFS",
//             rating: "3.35",
//             created_at: "2023-03-06T11:03:32.000000Z",
//             updated_at: "2023-04-07T18:51:39.000000Z",
//             deleted_at: null,
//           },
//         ],
//       },
//       categories: [
//         {
//           id: 16,
//           name: "Errors",
//           image: "errors.png",
//           type: "stamp_items",
//           parent_id: null,
//           created_at: "2023-03-06T09:54:50.000000Z",
//           updated_at: "2023-03-06T09:54:50.000000Z",
//           deleted_at: null,
//           image_url:
//             "https://devapi.stampbox.com/storage/category-images/errors.png",
//           pivot: {
//             categorizable_id: 33,
//             category_id: 16,
//             categorizable_type: "StampItem",
//           },
//         },
//       ],
//       albums: [],
//       medias: [
//         {
//           id: 113,
//           user_id: 13,
//           is_stamp: 1,
//           media: "users/user-13/item-media/16799213613773.png",
//           linked_with: "stamp",
//           type: "actual",
//           created_at: "2023-03-27T12:49:21.000000Z",
//           updated_at: "2023-03-27T12:49:21.000000Z",
//           deleted_at: null,
//           media_url:
//             "https://d30hji56ulrnvw.cloudfront.net/users/user-13/item-media/16799213613773.png",
//           pivot: {
//             mediable_id: 33,
//             media_id: 113,
//             mediable_type: "StampItem",
//           },
//         },
//       ],
//       trade_offers: [],
//     },
//     {
//       id: 43,
//       user_id: 11,
//       name: "Queen Stamp",
//       uuid: "I-Afa1920-2358299",
//       status: ["FOR_TRADE", "FOR_AUCTION", "FOR_SALE"],
//       country: "Afars &amp; Issas",
//       year_issued: "1920",
//       denomination: "12",
//       perforation: null,
//       color: null,
//       condition: "Used",
//       grade: null,
//       format: "Strip",
//       total_stamps_issued: null,
//       coins_value: 2000,
//       related_set_stamps_count: null,
//       quality: ["Lightly Hinged (LH)", "Hinged Remaining (HR)"],
//       shape: null,
//       quantity_owned: {
//         used: null,
//         mint: null,
//       },
//       issue_type: null,
//       created_by: 11,
//       updated_by: 11,
//       description: null,
//       created_at: "2023-04-05T17:37:25.000000Z",
//       updated_at: "2023-04-06T14:17:44.000000Z",
//       deleted_at: null,
//       flag_tickets_count: 0,
//       is_flagged_by_current_user: 0,
//       is_wishable: 0,
//       is_attached_in_auctions: 0,
//       is_attached_in_trades: 0,
//       is_attached_in_supply: 1,
//       is_item_placed_in_trade_offer: 0,
//       catalogue_number: [
//         {
//           id: 73,
//           stamp_item_id: 43,
//           type: "Stanly Gibson",
//           number: "12",
//           year: 2016,
//           value: "20.00",
//         },
//       ],
//       user: {
//         id: 11,
//         first_name: "John",
//         last_name: "Doe",
//         username: "john",
//         image: "users/user-11/profile-images/16799371237028.png",
//         cover_image: null,
//         email: "nadape5178@wifame.com",
//         phone: "+12708175769",
//         description: null,
//         language: "Albanian (Albania)",
//         gender: "Male",
//         dob: 1998,
//         is_email_verified: 1,
//         uid: "HeZUf9KE7nNsBiXflSoN48ZyB9Y2",
//         coins: 1069,
//         wallet_balance: 42,
//         mrs_badge: "Beginner",
//         caco_level: "Partner",
//         type: "member",
//         status: "Active",
//         created_at: "2023-03-06T10:15:12.000000Z",
//         updated_at: "2023-04-06T16:05:19.000000Z",
//         stripe_id: "cus_NTYAk9aXTpWKly",
//         pm_type: "visa",
//         pm_last_four: "4242",
//         trial_ends_at: null,
//         deleted_at: null,
//         full_name: "John Doe",
//         image_url:
//           "https://stampbox-project-dev.s3.us-east-2.amazonaws.com/users/user-11/profile-images/16799371237028.png",
//         cover_image_url:
//           "https://devapi.stampbox.com/default-images/banner_thumbnail.png",
//         rating: 2.5,
//         is_payment_method_attached: true,
//         profile_viewable_name: "John Doe",
//         ratings: [
//           {
//             id: 11,
//             user_id: 11,
//             type: "TFS",
//             rating: "2.50",
//             created_at: "2023-03-06T10:15:12.000000Z",
//             updated_at: "2023-03-31T10:44:05.000000Z",
//             deleted_at: null,
//           },
//         ],
//       },
//       categories: [],
//       albums: [],
//       medias: [
//         {
//           id: 91,
//           user_id: 11,
//           is_stamp: 1,
//           media: "users/user-11/item-media/16794225627473.png",
//           linked_with: "stamp",
//           type: "actual",
//           created_at: "2023-03-21T18:16:02.000000Z",
//           updated_at: "2023-03-21T18:27:25.000000Z",
//           deleted_at: null,
//           media_url:
//             "https://d30hji56ulrnvw.cloudfront.net/users/user-11/item-media/16794225627473.png",
//           pivot: {
//             mediable_id: 43,
//             media_id: 91,
//             mediable_type: "StampItem",
//           },
//         },
//       ],
//       trade_offers: [],
//     },
//     {
//       id: 44,
//       user_id: 14,
//       name: "Cold Snaps",
//       uuid: "I-Uni2015-7268011",
//       status: ["FOR_SALE", "PRIVATE"],
//       country: "United States",
//       year_issued: "2015",
//       denomination: "22",
//       perforation: "2",
//       color: "Magenta",
//       condition: "Mint",
//       grade: null,
//       format: "Booklet",
//       total_stamps_issued: "200",
//       coins_value: 2100,
//       related_set_stamps_count: "122",
//       quality: ["Heavily Hinged (HH)"],
//       shape: "Mix",
//       quantity_owned: {
//         used: "12",
//         mint: "12",
//       },
//       issue_type: "N/A",
//       created_by: 14,
//       updated_by: 14,
//       description:
//         "this is the stamp that relate to all the pr f lincon gallery.",
//       created_at: "2023-04-06T16:45:44.000000Z",
//       updated_at: "2023-04-06T16:45:44.000000Z",
//       deleted_at: null,
//       flag_tickets_count: 0,
//       is_flagged_by_current_user: 0,
//       is_wishable: 0,
//       is_attached_in_auctions: 0,
//       is_attached_in_trades: 0,
//       is_attached_in_supply: 0,
//       is_item_placed_in_trade_offer: 0,
//       catalogue_number: [
//         {
//           id: 74,
//           stamp_item_id: 44,
//           type: "Stanly Gibson",
//           number: "233",
//           year: 2020,
//           value: "21.00",
//         },
//       ],
//       user: {
//         id: 14,
//         first_name: "Adnan",
//         last_name: "Ali",
//         username: "adnan1678101873337",
//         image: null,
//         cover_image: null,
//         email: "adnan@pixarsart.com",
//         phone: "+92 900 786 0123",
//         description:
//           "this is the AdAli who has experties in the stamps ranks of the world.",
//         language: "Afar (Djibouti)",
//         gender: "Male",
//         dob: 2000,
//         is_email_verified: 1,
//         uid: "HTxt3zGnAQNPZSTJoEAQIiP3jKJ2",
//         coins: 57,
//         wallet_balance: 20,
//         mrs_badge: "Beginner",
//         caco_level: "Enthusiast",
//         type: "member",
//         status: "Active",
//         created_at: "2023-03-06T11:24:34.000000Z",
//         updated_at: "2023-04-06T11:40:02.000000Z",
//         stripe_id: "cus_NTZIp5MWPz3gTb",
//         pm_type: "visa",
//         pm_last_four: "4242",
//         trial_ends_at: null,
//         deleted_at: null,
//         full_name: "Adnan Ali",
//         image_url: "https://devapi.stampbox.com/default_user_image.png",
//         cover_image_url:
//           "https://devapi.stampbox.com/default-images/banner_thumbnail.png",
//         rating: 0,
//         is_payment_method_attached: true,
//         profile_viewable_name: "Adnan Ali",
//         ratings: [
//           {
//             id: 14,
//             user_id: 14,
//             type: "TFS",
//             rating: "0.00",
//             created_at: "2023-03-06T11:24:34.000000Z",
//             updated_at: "2023-03-06T11:24:34.000000Z",
//             deleted_at: null,
//           },
//         ],
//       },
//       categories: [
//         {
//           id: 35,
//           name: "Postmarks",
//           image: "postmarks.png",
//           type: "stamp_items",
//           parent_id: null,
//           created_at: "2023-03-06T09:54:50.000000Z",
//           updated_at: "2023-03-06T09:54:50.000000Z",
//           deleted_at: null,
//           image_url:
//             "https://devapi.stampbox.com/storage/category-images/postmarks.png",
//           pivot: {
//             categorizable_id: 44,
//             category_id: 35,
//             categorizable_type: "StampItem",
//           },
//         },
//       ],
//       albums: [],
//       medias: [
//         {
//           id: 11,
//           user_id: 14,
//           is_stamp: 1,
//           media: "users/user-14/item-media/16781044112195.jpg",
//           linked_with: "stamp",
//           type: "actual",
//           created_at: "2023-03-06T12:06:51.000000Z",
//           updated_at: "2023-03-21T10:23:25.000000Z",
//           deleted_at: null,
//           media_url:
//             "https://d30hji56ulrnvw.cloudfront.net/users/user-14/item-media/16781044112195.jpg",
//           pivot: {
//             mediable_id: 44,
//             media_id: 11,
//             mediable_type: "StampItem",
//           },
//         },
//       ],
//       trade_offers: [],
//     },
//   ],
//   request: {
//     request_type: "GET",
//     payload: {
//       similarable_type: "stamp_item",
//       similarable_id: "9",
//     },
//   },
// };
