export const trialPlan = {
  feature: {
    title: "30 Day Trial",
    access: "International",
    coinsAllocation: 0,
    ad: "With Ads $0.00/month",
  },
  "App Features": [
    "Access to:",
    "APP Scanning & Uploading to StampBox",
    "Do I have it? Search my Collection",
    "ALL WEB Features in your APP",
  ],
  "Profile Access": [
    "Access to Selecting:",
    "Specialised Countries: 5",
    "Specialised Categories: 3",
    "Specialised Topics: 5",
    "Wishlist: 50",
    "Blogs: 5",
    "Clubs: 10",
    "Friend Invitations: 10/month",
  ],
  Search: [
    "Access to:",
    "Search Catalogue - unlimited international",
    "Search Marketplace- unlimited international",
    "Search Users- unlimited international",
    "Search Clubs - unlimited international",
    "Search Stores - unlimited international",
    "Search Wish Lists - unlimited international",
  ],
  Calendar: ["Access to:", "Events: Full Access"],
  Catalogue: [
    "Access to:",
    "Search",
    "Contribution: Unlimited",
    "Flagging: Unlimited",
  ],
  Marketplace: [
    "Access to:",
    "Trade: Unlimited",
    "Buy: Unlimited",
    "Sell: Unlimited: Stamps and Supplies",
    "Bounties: View & Post",
    "Auctions: Create, bid",
  ],
  "My Collection": [
    "Access to:",
    "StampBox: up to 100 Items",
    "Albums: 5",
    "Inventory Reports: Basic",
    "Wishlist: Up to 10",
  ],
  "My Network": [
    "Access to:",
    "Groups: Unlimited International - View, Join, Participate, Create & Manage",
    "Messaging: Unlimited International",
    "Emails",
    "Notifications",
    "Contacts",
    "Conections",
    "Followers",
    "Directories",
  ],
  "My Store": [
    "Access to:",
    "Sell: Stamps and Supplies (unlimited)",
    "Buy: Internationally",
    "Auctions: Unlimited",
    "Campaigns: Unlimited",
  ],
  Communications: [
    "Access to:",
    "Chat: View, Join & Participate",
    "Posting",
    "Email",
    "Social Media Conections",
  ],
  Events: [
    "Access to:",
    "Events: View, Signup, Create",
    "Exhibits: Create, Participate, View, Rate",
  ],
  Resources: [
    "Access to:",
    "Catalogue",
    "Organizations",
    "Dealers",
    "Expertizing",
    "Whitepapers",
    "How-to",
    "FAQs",
  ],
  Clubs: ["Access to:", "View", "Join & Participate"],
};
export const businessPlan = {
  feature: {
    title: "Business Plan",
    access: "International",
    coinsAllocation: 50,
    ad: "Ad Fre $150/year (or 1500 ₡oins)",
  },
  "App Features": [
    "Access to:",
    "APP Scanning & Uploading to StampBox",
    "Do I have it? Search my Collection",
    "ALL WEB Features in your APP",
  ],
  "Profile Access": [
    "Access to Selecting:",
    "Specialised Countries: Unlimited",
    "Specialised Categories: All",
    "Specialised Topics: Unlimited",
    "Wishlist: Unlimited",
    "Blogs: Unlimited",
    "Clubs: Unlimited",
    "Friend Invitations: Unlimited",
  ],
  Search: [
    "Access to:",
    "Search Catalogue - unlimited international",
    "Search Marketplace- unlimited international",
    "Search Users- unlimited international",
    "Search Clubs - unlimited international",
    "Search Stores - unlimited international",
    "Search Wish Lists - unlimited international",
    "Search Auctions - unlimited international",
    "Search Events - unlimited international",
  ],
  Calendar: ["Access to:", "Events: View, Participate, Create, Broadcast"],
  Catalogue: [
    "Access to:",
    "Search & View",
    "Contribution: Unlimited",
    "Flagging: Unlimited",
  ],
  Marketplace: [
    "Access to:",
    "Trade: Unlimited",
    "Buy: Unlimited",
    "Sell: Unlimited: Stamps and Supplies",
    "Bounties: View, Post, Hunt and Submit",
    "Auctions: View, Create & Bid",
  ],
  "My Collection": [
    "Access to:",
    "StampBox: Unlimited",
    "Albums: Unlimited",
    "Inventory Reports: Full",
    "Wishlist: Unlimited",
  ],
  "My Network": [
    "Access to:",
    "Groups: Unlimited International - View, Join, Participate, Create & Manage",
    "Messaging: Unlimited International",
    "Emails",
    "Notifications",
    "Contacts",
    "Conections",
    "Followers",
    "Directories",
  ],
  "My Store": [
    "Access to:",
    "Sell: Stamps and Supplies (unlimited)",
    "Buy: Internationally",
    "Auctions: Unlimited",
    "Campaigns: Unlimited",
  ],
  Communications: [
    "Access to:",
    "Chat: View, Join & Participate",
    "Posting",
    "Email",
    "Social Media Conections",
  ],
  Events: [
    "Access to:",
    "Events: View, Signup, Create",
    "Exhibits: Create, Participate, View, Rate",
  ],
  Resources: [
    "Access to:",
    "Catalogue",
    "Organizations",
    "Dealers",
    "Expertizing",
    "Whitepapers",
    "How-to",
    "FAQs",
  ],
  Clubs: ["Access to:", "View", "Join & Participate", "Create", "Manage"],
};

export const freeAcctPlan = {
  feature: {
    title: "Free Account",
    access: "Locally (Country)",
    coinsAllocation: 0,
    ad: "With Ads $0.00/month",
  },
  "APP Features": [" Access to", "APP Scanning & Uploading to StampBox"],
  "Profile Access": [
    "Access to Selecting",
    "Specialised Countries: 3",
    "Specialised Categories: 2",
    "Specialised Topics: 3",
    "Wishlist: 0",
    "Blogs: 2",
    "Clubs: 0",
    "Friend Invitations: 5 / month",
  ],
  Search: [
    "Access to",
    "Search Marketplace - For Trade, For Sale",
    "Search Users - Locally(Country)",
    "Search Clubs - Locally(Country)",
    "Search Stores - Locally(Country)",
  ],
  Calendar: [" Access to", "Events: View"],
  Catalogue: ["Access to", "Search & View"],
  Marketplace: ["Access to", "Trade: Locally(Country)", "Buy: Unlimited"],
  "My Collection": [
    "Access to",
    "StampBox: up to 100 Items",
    "Albums: 5",
    "Inventory Reports: Basic",
    "Wishlist: Up to 10",
  ],
  "My Network": ["Access to", "Groups: local(Country)", "Messaging: Limited"],
  Events: ["Access to:", , "Events: View"],
  Resources: [
    "Access to:",
    ,
    "Catalogue",
    "Organization",
    "Dealer",
    "Expertizin",
    "Whitepapers",
    "How - to",
    "FAQ",
  ],
  Clubs: ["Access to:", "View"],
};

export const basicPlan = {
  feature: {
    title: "Basic Plan",
    access: "Locally (Country)",
    coinsAllocation: 10,
    ad: "Ad Free $60/year (or 600 ₡oins)",
  },
  "App Features": [
    "Access to",
    "APP Scanning & Uploading to StampBox",
    "Limited Access WEB Features in your APP",
  ],
  "Profile Access": [
    "Access to Selecting",
    "Specialised Countries: 3",
    "Specialised Categories: 3",
    "Specialised Topics: 3",
    "Wishlist: 20",
    "Blogs: 3",
    "Clubs: 5",
    "Friend Invitations: 10 / month",
  ],
  Search: [
    "Access to",
    "Search Catalogue - unlimited international",
    "Search Marketplace - For Trade, For Sale",
    "Search Users - Locally(Country)",
    "Search Clubs - Locally(Country)",
    "Search Stores - Locally(Country)",
  ],
  Calendar: [" Access to", "Events: View, Participate"],
  Catalogue: ["Access to", "Search & View"],
  Marketplace: [
    "Access to",
    "Trade: Locally(Country)",
    "Buy: Locally(Country)",
    "Bounty: View",
  ],
  "My Collection": [
    "Access to",
    "StampBox: up to 500 Items",
    "Albums: 10 Albums",
    "Inventory Reports: Basic",
    "Wishlist: Up to 50",
  ],
  "My Network": [
    "Access to",
    "Groups: local(Country) - View, Join & Participate",
    "Messaging: Limited",
    "Notifications",
    "Contacts",
    "Conections",
    "Followers",
    "Directories",
  ],
  "My Store": ["Access to:", , "Buy: Only Locally(locally)", "Auctions: View"],
  Communications: [
    "Access to:",
    "Chat: View, Join & Participate",
    "Posting",
    "Email",
    "Social Media Conections",
  ],
  Events: ["Access to:", , "Events: View, Signup", "Exhibits: View"],
  Resources: [
    "Access to:",
    ,
    "Catalogue",
    "Organization",
    "Dealer",
    "Expertizin",
    "Whitepapers",
    "How - to",
    "FAQ",
  ],
  Clubs: ["Access to:", , "View", "Join & Participate"],
};

export const premiumPlan = {
  feature: {
    title: "Premium Plan",
    access: "International",
    coinsAllocation: 30,
    ad: "Ad Free $100/year (or 1000 ₡oins)",
  },
  "APP Features": [
    " Access to",
    "APP Scanning & Uploading to StampBox",
    "Do I have it ? Search my Collection",
    "Access to ALL WEB Features in your APP",
  ],
  "Profile Access": [
    "Access to Selecting",
    "Specialised Countries: 5",
    "Specialised Categories: 3",
    "Specialised Topics: 5",
    "Wishlist: 50",
    "Blogs: 5",
    "Clubs: 15",
    "Friend Invitations: 20 / month",
  ],
  Search: [
    "Access to",
    "Search Catalogue - unlimited international",
    "Search Marketplace - For Trade, For Sale, Bounties, Auctions",
    "Search Users - unlimited international",
    "Search Clubs - unlimited international",
    "Search Stores - unlimited international",
    "Search Wish Lists - unlimited international",
    "Search Auctions - unlimited international",
    "Search Events - unlimited international",
  ],
  Calendar: [" Access to", "Events: View, Participate, Create, Broadcast"],
  Catalogue: [
    "Access to",
    "Search & View",
    "Contribute: Unlimited",
    "Flagging: Unlimited",
  ],
  Marketplace: [
    "Access to",
    "Trade: Unlimited",
    "Buy: Unlimited",
    "Sell: Unlimited: Stamps",
    "Bounties: View, Post, Hunt and Submit",
    "Auctions: View & Bid",
  ],
  "My Collection": [
    "Access to",
    "StampBox: Unlimited",
    "Albums: Unlimited",
    "Inventory Reports: Full",
    "Wishlist: Unlimited",
  ],
  "My Network": [
    "Access to",
    "Groups: Unlimited International - View, Join & Participate - Create & Manage",
    "Messaging: Unlimited International",
    "Notifications",
    "Contacts",
    "Conections",
    "Followers",
    "Directories",
  ],
  "My Store": [
    "Access to:",
    "Sell: Only stamps",
    "Buy: Internationally",
    "Auctions: View, Bid, Create",
  ],
  Communications: [
    "Access to:",
    ,
    "Chat: View, Join & Participate",
    "Posting",
    "Email",
    "Social Media Conections",
  ],
  Events: [
    "Access to:",
    ,
    "Events: View, Signup, Create",
    "Exhibits: Create, Participate, View, Rate.",
  ],
  Resources: [
    "Access to:",
    ,
    "Catalogue",
    "Organization",
    "Dealer",
    "Expertizin",
    "Whitepapers",
    "How - to",
    "FAQ",
  ],
  Clubs: ["Access to:", , "View", "Join & Participate", "Create", "Manage"],
};
